Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

AllCops:
  Exclude:
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Documentation:
  Enabled: false
