Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

AllCops:
  Exclude:
    - '**/Rakefile'
    - '**/*.gemspec'
    - '**/console'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'lib/rest_my_case/accusation_attorneys/**/*'
    - 'lib/rest_my_case/validator/errors.rb'

Documentation:
  Enabled: false
