#!/usr/bin/ruby

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__))

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

require 'rubygems'
require 'bundler'

Bundler.require(:default, 'development')


require 'spec/support/perform'

binding.pry
